<a href="https://colab.research.google.com/github/Annamjohn/Python/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]
